### PR TITLE
basic faq

### PR DESCRIPTION
**Pull request by minsooerickim**
Same structure as the one from citrus hack faq. Wasn't sure what questions to put so I just copied some Qs from Citrus hack faq

### CODE REVIEW

**Comment by rajbirjohar** [comment]
@minsooerickim 
Would suggest converting from class component to functional component to stay within our project scopes. Also noticed you installed styled-components but I don't see where you used them? I would like to avoid mixing css libraries if possible so it would be a good idea to stick to css modules.

Edit: Removing styled-components should also fix your merge conflict.

**Comment by minsooerickim** [comment]
I removed the styled-components and I also changed "Accordion.js" and "faq.js" from class components to function components, but I wasn't really sure how to implement FaqSection.js as a function component since it uses a state method. Do you want me to still request a pull request with the new changes?

**Comment by rajbirjohar** [comment]
[Check this out.](https://nimblewebdeveloper.com/blog/convert-react-class-to-function-component)

**Comment by minsooerickim** [comment]
thanks for the article, it actually helped a ton

**Pull request merged**
